apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galaxy-health-bridge
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: galaxy-health-bridge
